const data = {
    products: [
        {
            _id:'1',
            name: 'Product 1',
            category: 'Pet Product',
            image: '/images/LuckysPetshopLogo.jpg',
            price: 30,
            countInStock: 10,
            brand: 'Sample Brand',
            rating: 5,
            numReviews: 10,
            description: 'Pet Essentials',
        },
        {
            _id:'2',
            name: 'Product 2',
            category: 'Pet Product',
            image: '/images/LuckysPetshopLogo.jpg',
            price: 60,
            countInStock: 20,
            brand: 'Sample Brand',
            rating: 3,
            numReviews: 10,
            description: 'Pet Essentials',
        },
        {
            _id:'3',
            name: 'Product 3',
            category: 'Pet Product',
            image: '/images/LuckysPetshopLogo.jpg',
            price: 90,
            countInStock: 30,
            brand: 'Sample Brand',
            rating: 4.5,
            numReviews: 10,
            description: 'Pet Essentials',
        },
        {
            _id:'4',
            name: 'Product 4',
            category: 'Pet Product',
            image: '/images/LuckysPetshopLogo.jpg',
            price: 120,
            countInStock: 40,
            brand: 'Sample Brand',
            rating: 3.5,
            numReviews: 10,
            description: 'Pet Essentials',
        },
        {
            _id:'5',
            name: 'Product 5',
            category: 'Pet Product',
            image: '/images/LuckysPetshopLogo.jpg',
            price: 150,
            countInStock: 50,
            brand: 'Sample Brand',
            rating: 4.5,
            numReviews: 10,
            description: 'Pet Essentials',
        },
        {
            _id:'6',
            name: 'Product 6',
            category: 'Pet Product',
            image: '/images/LuckysPetshopLogo.jpg',
            price: 180,
            brand: 'Sample Brand',
            countInStock: 0,
            rating: 4.5,
            numReviews: 10,
            description: 'Pet Essentials',
        },
    ],
};
export default data;