import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
          name: 'Edward',
          email: 'admin@example.com',
          password: bcrypt.hashSync('1234', 8),
          isAdmin: true,
        },
        {
          name: 'Jerome',
          email: 'user@example.com',
          password: bcrypt.hashSync('1234', 8),
          isAdmin: false,
        },
      ],

    products: [
        {
            name: 'Sample Poultry Supply',
            category: 'Poultry Supply',
            image: '/images/LuckysPetshopLogo.jpg',
            price: 30.00,
            countInStock: 10,
            brand: 'Poultry Supply',
            rating: 0.0,
            numReviews: 0,
            description: 'Pet Essentials',
        },
        {
            name: 'Sample Fish Food Pellets',
            category: 'Fish Food Pellets',
            image: '/images/LuckysPetshopLogo.jpg',
            price: 60.00,
            countInStock: 20,
            brand: 'Fish Food Pellets',
            rating: 0.0,
            numReviews: 0,
            description: 'Pet Essentials',
        },
        {
            name: 'Sample Bath Essential',
            category: 'Pet Bath Essentials',
            image: '/images/LuckysPetshopLogo.jpg',
            price: 90.00,
            countInStock: 30,
            brand: 'Pet Bath Essentials',
            rating: 0.0,
            numReviews: 10,
            description: 'Pet Essentials',
        },
        {
            name: 'Sample Pet Cologne',
            category: 'Pet Cologne',
            image: '/images/LuckysPetshopLogo.jpg',
            price: 120.00,
            countInStock: 40,
            brand: 'Pet Cologne',
            rating: 0.0,
            numReviews: 10,
            description: 'Pet Essentials',
        },
        {
            name: 'Sample Pet Diaper',
            category: 'Pet Diaper',
            image: '/images/LuckysPetshopLogo.jpg',
            price: 150.00,
            countInStock: 50,
            brand: 'Pet Diaper',
            rating: 0.0,
            numReviews: 10,
            description: 'Pet Essentials',
        },
        {
            name: 'Sample Pet Accessories',
            category: 'Pet Accessories',
            image: '/images/LuckysPetshopLogo.jpg',
            price: 180.00,
            brand: 'Pet Accessories',
            countInStock: 0,
            rating: 0.0,
            numReviews: 10,
            description: 'Pet Essentials',
        },
        {
            name: 'Vitality ValueMeal Puppy 1kg',
            category: 'Dog Food',
            image: '/images/Vitality ValueMeal Puppy Dog Food.png',
            price: 169.00,
            brand: 'Vitality ValueMeal',
            countInStock: 20,
            rating: 0.0,
            numReviews: 0,
            description: 'High quality Australian lamb & beef dog food for puppies’ dogs that does not break the bank',
        },
        {
            name: 'Vitality ValueMeal Adult 1kg',
            category: 'Dog Food',
            image: '/images/Vitality Classic Dog Food Adult Lamb and Beef Flavor.png',
            price: 179.00,
            brand: 'Vitality ValueMeal',
            countInStock: 20,
            rating: 0.0,
            numReviews: 0,
            description: 'The high-grade ingredients of lamb, beef, cereals and fats are carefully balanced to nourish your dog and result in high digestibility, the formation of small solid stools and substantially reduce odor. The absence of a foul smell and wet stool ensures a healthy and clean surrounding for your pet and family.',
        },
        {
            name: 'Holistic Recipe Adult Blue 1kg',
            category: 'Dog Food',
            image: '/images/Holistic Recipe Adult Dog Food.png',
            price: 390.00,
            brand: 'Holistic Recipe',
            countInStock: 0,
            rating: 0.0,
            numReviews: 0,
            description: 'High digestibility, Healthy & balanced diet with high quality ingredients, Contains green tea, lamb meal & brewer’s rice.',
        },
        {
            name: 'Holistic Recipe Pregnant Pink 1kg',
            category: 'Dog Food',
            image: '/images/Holistic Recipe Adult Dog Food.png',
            price: 390.00,
            brand: 'Holistic Recipe',
            countInStock: 25,
            rating: 0.0,
            numReviews: 0,
            description: 'Formulated for puppies & pregnant/lactating dog.',
        },
        {
            name: 'Purina ALPO Prime Cuts® Beef 1kg',
            category: 'Dog Food',
            image: '/images/Purina ALPO Prime Cuts Dry Dog Food Savory Beef Flavor.png',
            price: 193.00,
            brand: 'Purina ALPO',
            countInStock: 25,
            rating: 0,
            numReviews: 0,
            description: 'Every bag is packed with all the good stuff your adult dog needs. Once he chomps into these hearty shapes and crunchy textures with savory beef flavor, there’s no stopping him from devouring every last crumb. Bite after bite, bowl after bowl, Prime Cuts dry dog food is always a favorite.',
        },
        {
            name: 'Purina Alpo Adult Dog Food Beef Liver and Vegetables',
            category: 'Dog Food',
            image: '/images/Purina Alpo Adult Dog Food Beef Liver and Vegetables.png',
            price: 286.00,
            brand: 'Purina Alpo',
            countInStock: 25,
            rating: 0.0,
            numReviews: 0,
            description: 'The irresistible beef tastes your dog loves with the complete nutrition that he needs.',
        },
        {
            name: 'PEDIGREE Dry Mini Grilled Liver Flavour',
            category: 'Dog Food',
            image: '/images/PEDIGREE Dry Mini Grilled Liver Flavour.png',
            price: 286.00,
            brand: 'PEDIGREE',
            countInStock: 25,
            rating: 0.0,
            numReviews: 0,
            description: 'The small breeds are different from the medium large ones. The small breeds will reach their adulthood earlier than the medium large ones, They have smaller oral cavity, and teethThey are pickier.',
        },
        {
            name: 'Power Cat Fresh Ocean Tuna Cat Dry Food',
            category: 'Cat Food',
            image: '/images/Power Cat Fresh Ocean Tuna Cat Dry Food.png',
            price: 255.00,
            brand: 'Power Cat',
            countInStock: 25,
            rating: 0.0,
            numReviews: 0,
            description: 'PowerCat Dry series is made with the best and natural ingredients. It is indeed a delicacy for all cats.It contains 32% protein, which are beneficial to the health of cats. PowerCat Dry Cat Food comes in two flavors Fresh Fish & Tuna and Fresh.',
        },
        {
            name: 'Power Cat Kitten Dry Food',
            category: 'Cat Food',
            image: '/images/Power Cat Kitten Dry Food.png',
            price: 145.00,
            brand: 'Power Cat',
            countInStock: 25,
            rating: 0.0,
            numReviews: 0,
            description: 'PowerCat Dry series is made with the best and natural ingredients. It is indeed a delicacy for all cats.It contains 32% protein, which are beneficial to the health of cats. PowerCat Dry Cat Food comes in two flavors Fresh Fish & Tuna and Fresh.',
        },
        {
            name: 'Monge Special Cat Chicken & Turkey Cat Dry Food',
            category: 'Cat Food',
            image: '/images/Monge Special Cat Chicken & Turkey Cat Dry Food.png',
            price: 145.00,
            brand: 'Special Cat',
            countInStock: 25,
            rating: 0.0,
            numReviews: 0,
            description: 'Monge Special Chicken and Turkey is packed with fresh meat for 100% complete nutrition. Formulated with low magnesium content to keep kidneys healthy, easy on the digestion, and great at tartar prevention for healthy teeth. This chicken and turkey flavor is very delicious for cats and kittens alike.',
        },
        {
            name: 'Whiskas Dry Cat Food Adult',
            category: 'Cat Food',
            image: '/images/WHISKAS DRY CAT FOOD ADULT 1 years.png',
            price: 276.00,
            brand: 'Whiskas',
            countInStock: 25,
            rating: 0.0,
            numReviews: 0,
            description: 'Crunchy, munchy and delicious chunks packed with real fish flavor and milk pockets. Made with high-quality ingredients that provide your pet Kitten with the nutrition it needs. The special blend of nutrients help supports the cats vital system.',
        },
        {
            name: 'WHISKAS® Junior Ocean Fish Flavor kitten',
            category: 'Cat Food',
            image: '/images/WHISKAS Junior Ocean Fish Flavor wMilk Dry Cat Food.png',
            price: 174.00,
            brand: 'Whiskas',
            countInStock: 25,
            rating: 0.0,
            numReviews: 0,
            description: 'Crunchy, munchy and delicious chunks packed with real fish flavor and milk pockets. Made with high-quality ingredients that provide your pet Kitten with the nutrition it needs. The special blend of nutrients help supports the cats vital system.',
        },
    ],
};
export default data;