import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
          name: 'Edward',
          email: 'admin@example.com',
          password: bcrypt.hashSync('1234', 8),
          isAdmin: true,
        },
        {
          name: 'Jerome',
          email: 'user@example.com',
          password: bcrypt.hashSync('1234', 8),
          isAdmin: false,
        },
      ],

    products: [
        {
            name: 'Product 1',
            category: 'Pet Product',
            image: '/images/LuckysPetshopLogo.jpg',
            price: 30,
            countInStock: 10,
            brand: 'Sample Brand',
            rating: 5,
            numReviews: 10,
            description: 'Pet Essentials',
        },
        {
            name: 'Product 2',
            category: 'Pet Product',
            image: '/images/LuckysPetshopLogo.jpg',
            price: 60,
            countInStock: 20,
            brand: 'Sample Brand',
            rating: 3,
            numReviews: 10,
            description: 'Pet Essentials',
        },
        {
            name: 'Product 3',
            category: 'Pet Product',
            image: '/images/LuckysPetshopLogo.jpg',
            price: 90,
            countInStock: 30,
            brand: 'Sample Brand',
            rating: 4.5,
            numReviews: 10,
            description: 'Pet Essentials',
        },
        {
            name: 'Product 4',
            category: 'Pet Product',
            image: '/images/LuckysPetshopLogo.jpg',
            price: 120,
            countInStock: 40,
            brand: 'Sample Brand',
            rating: 3.5,
            numReviews: 10,
            description: 'Pet Essentials',
        },
        {
            name: 'Product 5',
            category: 'Pet Product',
            image: '/images/LuckysPetshopLogo.jpg',
            price: 150,
            countInStock: 50,
            brand: 'Sample Brand',
            rating: 4.5,
            numReviews: 10,
            description: 'Pet Essentials',
        },
        {
            name: 'Product 6',
            category: 'Pet Product',
            image: '/images/LuckysPetshopLogo.jpg',
            price: 180,
            brand: 'Sample Brand',
            countInStock: 0,
            rating: 4.5,
            numReviews: 10,
            description: 'Pet Essentials',
        },
        {
            name: 'Vitality ValueMeal Puppy',
            category: 'Dog Food',
            image: '/images/Vitality ValueMeal Puppy Dog Food',
            price: 169,
            brand: 'Vitality ValueMeal',
            countInStock: 20,
            rating: 0,
            numReviews: 0,
            description: 'High quality Australian lamb & beef dog food for puppies’ dogs that does not break the bank',
        },
    ],
};
export default data;